Vagrant.configure("2") do |config|
  # FTP server
  config.vm.define "ftp-server" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "ftp-server"
    server.vm.network "private_network", ip: "192.168.56.10",virtualbox__intnet: "lan"

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update 2>/dev/null1
      sudo apt-get install vsftpd -y 2>/dev/null
      sudo systemctl enable vsftpd  2>/dev/null
      sudo systemctl start vsftpd
      sudo adduser --disabled-password --gecos "" ftpuser
      echo "ftpuser:1234" | sudo chpasswd
      sudo sed -i 's/^#write_enable=.*/write_enable=YES/' /etc/vsftpd.conf
      sudo systemctl restart vsftpd
    SHELL
  end

  # FTP client
  config.vm.define "ftp-client" do |client|
    client.vm.box = "debian/bookworm64"
    client.vm.hostname = "ftp-client"
    client.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: "lan"
    client.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update 2>/dev/null
    sudo apt-get install -y lftp 2>/dev/null
    SHELL
  end

  # MITM
  config.vm.define "attacker" do |attacker|
    attacker.vm.box = "ubuntu/jammy64"
    attacker.vm.hostname = "attacker"
    attacker.vm.network "private_network", ip: "192.168.56.12", virtualbox__intnet: "lan"
    attacker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    attacker.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update 2>/dev/null
    sudo apt-get install build-essential -y 2>/dev/null
    sudo apt-get install libpcap-dev -y 2>/dev/null
    sudo sysctl -w net.ipv4.ip_forward=1
    SHELL
  end
end