Vagrant.configure("2") do |config|
  # Serveur FTP
  config.vm.define "ftp-server" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "ftp-server"
    server.vm.network "private_network", ip: "192.168.56.10"

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y vsftpd
      sudo systemctl enable vsftpd
      sudo systemctl start vsftpd
      sudo adduser --gecos "" ftpuser
      echo "ftpuser:1234" | sudo chpasswd
      sudo sed -i 's/^#write_enable=.*/write_enable=YES/' /etc/vsftpd.conf
      sudo systemctl restart vsftpd
    SHELL
  end

  # Client FTP
  config.vm.define "ftp-client" do |client|
    client.vm.box = "debian/bookworm64"
    client.vm.hostname = "ftp-client"
    client.vm.network "private_network", ip: "192.168.56.11"

    client.vm.provision "shell", inline: "sudo apt update && sudo apt install -y lftp"
  end

  #attaquant
  config.vm.define "attacker" do |attacker|
    attacker.vm.box = "ubuntu/jammy64"
    attacker.vm.hostname = "attacker"
    attacker.vm.network "private_network", ip: "192.168.56.12"
    attacker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
  end
end